(function () {
  'use strict';

  /**
   * A mock service to contain the artists we want to use for
   * the SlamOff demo. This would normally be a remote service.
   */
  angular.module('slamOff').constant('tracksMock', {
    data: [
      {
        "kind": "track",
        "id": 217698674,
        "created_at": "2015/08/04 05:22:10 +0000",
        "user_id": 163135511,
        "duration": 113120,
        "commentable": true,
        "state": "finished",
        "original_content_size": 1213395,
        "last_modified": "2015/08/04 06:08:57 +0000",
        "sharing": "public",
        "tag_list": "walk voicemail depression love writing poetry slam spoken",
        "permalink": "endless-walk-voicemail",
        "streamable": true,
        "embeddable_by": "all",
        "downloadable": false,
        "purchase_url": null,
        "label_id": null,
        "purchase_title": null,
        "genre": "endless",
        "title": "Endless Walk Voicemail - SPOKEN WORD (o.m.m)",
        "description": "A poem written by me, (o.m.m)",
        "label_name": null,
        "release": null,
        "track_type": "recording",
        "key_signature": null,
        "isrc": null,
        "video_url": null,
        "bpm": null,
        "release_year": null,
        "release_month": null,
        "release_day": null,
        "original_format": "ogg",
        "license": "all-rights-reserved",
        "uri": "https://api.soundcloud.com/tracks/217698674",
        "user": {
          "id": 163135511,
          "kind": "user",
          "permalink": "wordlesswordsmith",
          "username": "WordlessWordsmith",
          "last_modified": "2015/08/04 06:09:56 +0000",
          "uri": "https://api.soundcloud.com/users/163135511",
          "permalink_url": "http://soundcloud.com/wordlesswordsmith",
          "avatar_url": "https://i1.sndcdn.com/avatars-000154608671-7s33lo-large.jpg"
        },
        "created_with": {
          "id": 3152,
          "kind": "app",
          "name": "SoundCloud Android",
          "uri": "https://api.soundcloud.com/apps/3152",
          "permalink_url": "http://soundcloud.com/apps/android",
          "external_url": "https://market.android.com/details?id=com.soundcloud.android"
        },
        "permalink_url": "http://soundcloud.com/wordlesswordsmith/endless-walk-voicemail",
        "artwork_url": "https://i1.sndcdn.com/artworks-000125287720-4jnj7q-large.jpg",
        "waveform_url": "https://w1.sndcdn.com/S5SIONhk48pU_m.png",
        "stream_url": "https://api.soundcloud.com/tracks/217698674/stream",
        "playback_count": 10,
        "download_count": 0,
        "favoritings_count": 2,
        "comment_count": 0,
        "attachments_uri": "https://api.soundcloud.com/tracks/217698674/attachments",
        "policy": "ALLOW",
        "monetization_model": "NOT_APPLICABLE"
      },
      {
        "kind": "track",
        "id": 219197981,
        "created_at": "2015/08/14 09:45:46 +0000",
        "user_id": 44893562,
        "duration": 66618,
        "commentable": true,
        "state": "finished",
        "original_content_size": 2130432,
        "last_modified": "2015/08/14 09:45:47 +0000",
        "sharing": "public",
        "tag_list": "\"West Coast Eagles\" \"Fremantle Dockers\" AFL Drive \"John McGlue\" \"Alan Boyd\" \"Perth Poetry Festival\" poem \"slam poet\"",
        "permalink": "western-derby-by-the-antipoet-alan-boyd-1",
        "streamable": true,
        "embeddable_by": "all",
        "downloadable": false,
        "purchase_url": null,
        "label_id": null,
        "purchase_title": null,
        "genre": "Western Derby",
        "title": "'Western Derby' by the Antipoet Alan Boyd",
        "description": "Drive's resident poet Alan Boyd sets the news of the week to slam poetry and this week he couldn't escape writing about the Western Derby.\nOvercoming his hatred for West Coast and the Dockers, and his temporary writers block, Alan delivers a scathing football slam, ending with a score prediction.\n",
        "label_name": null,
        "release": null,
        "track_type": null,
        "key_signature": null,
        "isrc": null,
        "video_url": null,
        "bpm": null,
        "release_year": null,
        "release_month": null,
        "release_day": null,
        "original_format": "mp3",
        "license": "all-rights-reserved",
        "uri": "https://api.soundcloud.com/tracks/219197981",
        "user": {
          "id": 44893562,
          "kind": "user",
          "permalink": "720abcperth",
          "username": "720ABCPerth",
          "last_modified": "2015/08/23 12:29:03 +0000",
          "uri": "https://api.soundcloud.com/users/44893562",
          "permalink_url": "http://soundcloud.com/720abcperth",
          "avatar_url": "https://i1.sndcdn.com/avatars-000042462908-s6qrhd-large.jpg"
        },
        "permalink_url": "http://soundcloud.com/720abcperth/western-derby-by-the-antipoet-alan-boyd-1",
        "artwork_url": "https://i1.sndcdn.com/artworks-000126334424-fhn73x-large.jpg",
        "waveform_url": "https://w1.sndcdn.com/wJVnToBin2UM_m.png",
        "stream_url": "https://api.soundcloud.com/tracks/219197981/stream",
        "playback_count": 54,
        "download_count": 0,
        "favoritings_count": 1,
        "comment_count": 0,
        "attachments_uri": "https://api.soundcloud.com/tracks/219197981/attachments",
        "policy": "ALLOW",
        "monetization_model": "NOT_APPLICABLE"
      },
      {
        "kind": "track",
        "id": 198133366,
        "created_at": "2015/03/28 17:54:43 +0000",
        "user_id": 133757745,
        "duration": 43183,
        "commentable": true,
        "state": "finished",
        "original_content_size": 1039799,
        "last_modified": "2015/03/28 17:54:44 +0000",
        "sharing": "public",
        "tag_list": "",
        "permalink": "ideating-slam-poetry",
        "streamable": true,
        "embeddable_by": "all",
        "downloadable": false,
        "purchase_url": null,
        "label_id": null,
        "purchase_title": null,
        "genre": "slampoetry ",
        "title": "Ideating (slam Poetry)",
        "description": "",
        "label_name": null,
        "release": null,
        "track_type": null,
        "key_signature": null,
        "isrc": null,
        "video_url": null,
        "bpm": null,
        "release_year": null,
        "release_month": null,
        "release_day": null,
        "original_format": "mp3",
        "license": "all-rights-reserved",
        "uri": "https://api.soundcloud.com/tracks/198133366",
        "user": {
          "id": 133757745,
          "kind": "user",
          "permalink": "theozonelayer",
          "username": "Bryce H",
          "last_modified": "2015/03/28 21:44:22 +0000",
          "uri": "https://api.soundcloud.com/users/133757745",
          "permalink_url": "http://soundcloud.com/theozonelayer",
          "avatar_url": "https://a1.sndcdn.com/images/default_avatar_large.png"
        },
        "permalink_url": "http://soundcloud.com/theozonelayer/ideating-slam-poetry",
        "artwork_url": null,
        "waveform_url": "https://w1.sndcdn.com/OcOzxzBUui7h_m.png",
        "stream_url": "https://api.soundcloud.com/tracks/198133366/stream",
        "playback_count": 25,
        "download_count": 0,
        "favoritings_count": 0,
        "comment_count": 0,
        "attachments_uri": "https://api.soundcloud.com/tracks/198133366/attachments",
        "policy": "ALLOW",
        "monetization_model": "NOT_APPLICABLE"
      },
      {
        "id": 155886017,
        "kind": "user",
        "permalink": "special-stardust-va",
        "username": "Special Stardust VA",
        "last_modified": "2015/08/17 22:27:56 +0000",
        "uri": "https://api.soundcloud.com/users/155886017",
        "permalink_url": "http://soundcloud.com/special-stardust-va",
        "avatar_url": "https://i1.sndcdn.com/avatars-000148248252-bq7g71-large.jpg",
        "country": null,
        "first_name": null,
        "last_name": null,
        "full_name": "",
        "description": null,
        "city": null,
        "discogs_name": null,
        "myspace_name": null,
        "website": null,
        "website_title": null,
        "online": false,
        "track_count": 16,
        "playlist_count": 0,
        "plan": "Free",
        "public_favorites_count": 0,
        "followers_count": 2,
        "followings_count": 0,
        "subscriptions": []
      },
      {
        "id": 73207891,
        "kind": "user",
        "permalink": "wolfking4",
        "username": "Joshua Powell",
        "last_modified": "2015/08/23 05:25:00 +0000",
        "uri": "https://api.soundcloud.com/users/73207891",
        "permalink_url": "http://soundcloud.com/wolfking4",
        "avatar_url": "https://i1.sndcdn.com/avatars-000136338569-gmo41k-large.jpg",
        "country": "Canada",
        "first_name": "Joshua",
        "last_name": "Powell",
        "full_name": "Joshua Powell",
        "description": null,
        "city": "Bradford",
        "discogs_name": null,
        "myspace_name": null,
        "website": null,
        "website_title": null,
        "online": false,
        "track_count": 19,
        "playlist_count": 0,
        "plan": "Free",
        "public_favorites_count": 4,
        "followers_count": 11,
        "followings_count": 10,
        "subscriptions": []
      },
      {
        "id": 156871469,
        "kind": "user",
        "permalink": "mario-arango-4",
        "username": "Mario Arango",
        "last_modified": "2015/06/07 00:20:16 +0000",
        "uri": "https://api.soundcloud.com/users/156871469",
        "permalink_url": "http://soundcloud.com/mario-arango-4",
        "avatar_url": "https://i1.sndcdn.com/avatars-000149048764-kf4kkd-large.jpg",
        "country": null,
        "first_name": "Mario",
        "last_name": "Arango",
        "full_name": "Mario Arango",
        "description": null,
        "city": null,
        "discogs_name": null,
        "myspace_name": null,
        "website": null,
        "website_title": null,
        "online": false,
        "track_count": 1,
        "playlist_count": 0,
        "plan": "Free",
        "public_favorites_count": 0,
        "followers_count": 1,
        "followings_count": 0,
        "subscriptions": []
      },
      {
        "kind": "track",
        "id": 191153002,
        "created_at": "2015/02/14 20:26:03 +0000",
        "user_id": 30095276,
        "duration": 102330,
        "commentable": true,
        "state": "finished",
        "original_content_size": 1637021,
        "last_modified": "2015/02/14 20:31:28 +0000",
        "sharing": "public",
        "tag_list": "",
        "permalink": "poetry-slam",
        "streamable": true,
        "embeddable_by": "all",
        "downloadable": true,
        "purchase_url": null,
        "label_id": null,
        "purchase_title": null,
        "genre": "Poetry",
        "title": "Poetry Slam",
        "description": "Produced by Right Beat Radio, the perfect EP for Valentine's Day.",
        "label_name": null,
        "release": null,
        "track_type": null,
        "key_signature": null,
        "isrc": null,
        "video_url": null,
        "bpm": null,
        "release_year": null,
        "release_month": null,
        "release_day": null,
        "original_format": "mp3",
        "license": "all-rights-reserved",
        "uri": "https://api.soundcloud.com/tracks/191153002",
        "user": {
          "id": 30095276,
          "kind": "user",
          "permalink": "official_intel",
          "username": "Intel",
          "last_modified": "2015/08/06 20:35:18 +0000",
          "uri": "https://api.soundcloud.com/users/30095276",
          "permalink_url": "http://soundcloud.com/official_intel",
          "avatar_url": "https://i1.sndcdn.com/avatars-000159376653-h4e5pg-large.jpg"
        },
        "permalink_url": "http://soundcloud.com/official_intel/poetry-slam",
        "artwork_url": "https://i1.sndcdn.com/artworks-000106732990-3nqnpl-large.jpg",
        "waveform_url": "https://w1.sndcdn.com/gHBogjd6bgJ1_m.png",
        "stream_url": "https://api.soundcloud.com/tracks/191153002/stream",
        "download_url": "https://api.soundcloud.com/tracks/191153002/download",
        "playback_count": 49,
        "download_count": 5,
        "favoritings_count": 1,
        "comment_count": 1,
        "attachments_uri": "https://api.soundcloud.com/tracks/191153002/attachments",
        "policy": "ALLOW",
        "monetization_model": "NOT_APPLICABLE"
      },
      {
        "id": 21355158,
        "kind": "user",
        "permalink": "fleas-in-suits",
        "username": "Bearded Rizz Records",
        "last_modified": "2015/08/17 17:58:58 +0000",
        "uri": "https://api.soundcloud.com/users/21355158",
        "permalink_url": "http://soundcloud.com/fleas-in-suits",
        "avatar_url": "https://i1.sndcdn.com/avatars-000037143780-69y1vj-large.jpg",
        "country": "United States",
        "first_name": "Bearded Rizz",
        "last_name": "Records",
        "full_name": "Bearded Rizz Records",
        "description": null,
        "city": "Berlin, MD",
        "discogs_name": null,
        "myspace_name": null,
        "website": null,
        "website_title": null,
        "online": false,
        "track_count": 584,
        "playlist_count": 47,
        "plan": "Pro Plus",
        "public_favorites_count": 561,
        "followers_count": 293,
        "followings_count": 599,
        "subscriptions": [{"product": {"id": "creator-pro-unlimited", "name": "Pro Unlimited"}}]
      }
    ]
  });

  angular.module('slamOff')
    .config(function ($provide) {
      $provide.decorator('$httpBackend', angular.mock.e2e.$httpBackendDecorator);
    })
    .run(function ($httpBackend, tracksMock) {
      // $httpBackend.whenGET('/tracks').respond(200, tracksMock.data);
      $httpBackend.whenGET(/.*/).passThrough();
    });
})();
